config/routes.rb
Rails.application.routes.draw do
  root "employees#index"
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord

  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord

  before_save :set_retire_year

  belongs_to :department

  validates :name, presence: true
  validates :dob, presence: true

  def set_retire_year
    age = DateTime.now.year - self.dob.year
    self.retire_year = (60 - age) + DateTime.now.year
  end
end

app/models/employee_book.rb
class EmployeeBook

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  def index
    @employees = Employee.all.order(:name)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.valid?
      @employee.save
      redirect_to employees_path, notice: "Employee was successfully created."
    else
      flash[:errors] = @employee.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path, notice: "Employee was successfully updated."
    else
      flash[:errors] = @employee.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      flash[:notice] = "Employee was successfully destroyed."
    else
      flash[:errors] = 'Employee cannot destroy'
    end
    redirect_to employees_path
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :gender, :dob, :hobbies, :department_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, data: { turbo: false } do |form| %>
  <div class="row pb-3 pt-3">
    <div class="col-1">
      <%= form.label :name, class: 'col-form-label' %>
    </div>
    <div class="col-4">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row pb-3">
    <div class="col-1">
      <%= form.label :gender, class: 'col-form-label' %>
    </div>
    <div class="col-4">
      <%= form.radio_button :gender, "Female" %>
      <%= form.label :gender_female, "Female" %>

      <%= form.radio_button :gender, "Male" %>
      <%= form.label :gender_male, "Male" %>
    </div>
  </div>

  <div class="row pb-3">
    <div class="col-1">
      <%= form.label :dob, class: 'col-form-label' %>
    </div>
    <div class="col-4">
      <%= form.date_field :dob, value: Date.today, class: 'form-control' %>
    </div>
  </div>
  <div class="row pb-3">
    <div class="col-1">
      <%= form.label :department_id, class: 'col-form-label' %>
    </div>
    <div class="col-4">
      <%= form.select :department_id, Department.order(:name).map { |d| [d.name, d.id] },
      { prompt: '' }, class: 'form-select' %>
    </div>
  </div>

  <div class="row pb-3">
    <div class="col-1">
      <%= form.label :hobbies, class: 'col-form-label' %>
    </div>
    <div class="col-4">
      <%= form.text_area :hobbies, size: "70x5", class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-5 g-3 text-center">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/employees/edit.html.erb
<h5>Edit Employee / <%= @employee.name %></h5>

<% if flash[:errors] %>
  <div class="alert alert-danger col-5" role="alert">
    <% flash[:errors].each do |error| %>
      <p class="text-danger"><%= error %></p>
    <% end %>
  </div>
<% end %>

<%= render partial: 'employees/form', locals: {employee: @employee} %>

app/views/employees/index.html.erb
<div class="row pb-2">
  <div class="col-auto me-auto">
    <h5>List of Employees</h5>
  </div>
  <div class="col-auto">
    <%= link_to 'Add new Employee', new_employee_path, class: 'btn btn-primary' %>
  </div>
</div>
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <% flash.each do |name,message| %>
      <p class="text-success"><%= message%></p>
    <% end %>
  </div>
<% end %>
<% if flash[:errors] %>
  <div class="alert alert-danger" role="alert">
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  </div>
<% end %>
<div class="row">
  <table class="table table-info">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Gender</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Department</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.gender %></td>
          <td><%= employee.dob %></td>
          <td><%= employee.department.name %></td>
          <td>
            <%= button_to "Delete",employee_path(employee), method: :delete,
              class: "btn btn-danger" %>
          </td>
          <td><%= link_to 'Edit', edit_employee_path(employee)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<h5>New Employee</h5>
<% if flash[:errors] %>
  <div class="alert alert-danger col-5" role="alert">
    <% flash[:errors].each do |error| %>
      <p class="text-danger"><%= error %></p>
    <% end %>
  </div>
<% end %>
<%= render partial: 'employees/form', locals: {employee: @employee} %>

app/views/employees/test.html.erb
I am testing view

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/nav_bar'%>
      <div class="p-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Employee Book</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Employee', employees_path, class: 'nav-link active'  %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>